[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "netflow"
authors = [{name = "Rena Elkin"}]
version = "0.0.1"
description="Toolbox to compute information flow on a network and correlations between network modules"
readme = "README.md"
requires-python = "~=3.10" 
license = {file = "LICENSE.txt"}
dependencies = [
        'pandas==1.4.1',
        'networkx',
        'pot==0.8.2',
        'numpy==1.21.2',
        'cvxpy',
        'python-louvain',
        'ipykernel',
        'jupyterlab',
        'notebook==6.5.2',
        'jupyter_contrib_nbextensions',
        'gseapy>=1.0.4',
        'seaborn',
        'tqdm',
        'lifelines',
        'openpyxl',
        'scikit-learn',
        'fastcluster',
        'multiprocess',
        'dtreeviz',
        'plotly==5.9.0',
        'colorlog==6.7.0',
        'rich',
        'statsmodels',
        'dash==2.12.0',
        'dash-html-components==2.0.0',
        'dash-bootstrap-components==1.4.2',
        'dash_cytoscape==0.2.0',
        'pptree',
        'jupyter-dash==0.4.2',
        'dash-extensions',
        'dash-table==5.0.0',
	'bravado==12.0.1']

[project.optional-dependencies]
docs = [
    "sphinx>=7.0",
    "pydata-sphinx-theme>=0.15",
    "sphinx-design>=0.5",
    "sphinx-copybutton>=0.5",
    "sphinxcontrib-fulltoc>=1.2",
    "sphinxcontrib-bibtex>=2.6",
    "myst-nb>=1.0",
    "matplotlib>=3.5",         # needed by matplotlib.sphinxext.plot_directive
]

[project.urls]
"Homepage" = "https://github.com/areElkin/netflow/"

[tool.setuptools_scm]
write_to = "netflow/_version.py" # Write software version to this file
